### ISSUE TITLE
How to set maximum progress in this?

### ISSUE THREAD

**Issue by yuvaraj119** [aliab/circular-music-progressbar#10]

**Comment by aliab** [comment]
it will be available in next version. tnx

**Comment by yuvaraj119** [comment]
@aliab thanks for your reply i have added the maximum progress functionality and its working good. 

private float mMaxProgress = 100;

In onDraw method:
float sweetAngle = mProgressValue / mMaxProgress * 360;
canvas.drawArc(mBorderRect, 0, sweetAngle, false, mBorderPaint);

public void setMaxProgress(float maxProgress) {
        this.mMaxProgress = maxProgress;
        invalidate();
}
