### ISSUE TITLE
Anti Clockwise support

### ISSUE THREAD

**Issue by syedtalha** [aliab/circular-music-progressbar#11]
You could expose a custom attribute boolean that could control weather it progresses clockwise or anti clockwise. 

I'll be more than happy to do it in a pull request. 

Cheers

**Comment by aliab** [comment]
It seems a nice idea, very good if you send me a PR for this feature. otherwise, I will add this feature in near future.

**Comment by syedtalha** [comment]
@aliab  Can you assign me so that I can make a pull request?

**Comment by aliab** [comment]
@syedtalha fork project and send pull request in that way please.

**Comment by syedtalha** [comment]
@aliab Done  #13   . Pls release make a release if possible

**Comment by aliab** [comment]
I merged your PR. thank you.
